import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import navbar from "./components/navbar";
import Footer from "./footer";
import Navbar from "./components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Wania Azam Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{

  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar /> {children}   <Footer/ >
        </body>
    </html>
  );
}
